### ISSUE TITLE
[rpc]请问关于rpc模块中的client

### ISSUE THREAD

**Issue by fbaiesec** [hsyodyssey/Understanding-Ethereum-Go-version#1]
你好，最近我在阅读geth的源码，关于rpc模块中的client，想向您请教一下具体的细节。即令我困惑的是，什么情况下会去创建一个client实例？其次，为什么在server的代码中（serveCodec）也创建了client的实例？再次，client的dispatch方法是处理response的，为什么里面也包含handle.handleMsg来进行本地代码调用的逻辑（这本该是server接收到request然后调用本地方法并返回结果的逻辑链）？期待你的回复。

**Comment by hsyodyssey** [comment]
Hi 你好，下面是我的一些理解。

Q1. 什么情况下会去创建一个client实例？

比如在实例化geth的时候，会实例化Client实例，用于RPC调用。可以参考cmd/geth/consolecmd.go 中的remoteConsole函数。其中通过调用dialRPC，构造了一个Client的实例。

Q2: 为什么在server的代码中（serveCodec）也创建了client的实例？

根据它的用例 (rpc/ipc.go/ServeListener)，这么设计应该是起到了某种中介转发的作用。比如我们经常使用infrua的Server node充当中介，它的Server先接受到其他节点的请求，然后再使用本地生成的的Client向网络中的其他节点再转发。

Q3. 我没太懂你的问题。
