### ISSUE TITLE
目录里闲置电脑那一节为什么废弃了？

### ISSUE THREAD

**Issue by purevirtual** [hsyodyssey/Understanding-Ethereum-Go-version#26]
-[Deprecated] [怎么用闲置的电脑进行挖矿 | mining]
这一章为何废弃了？是担心法律问题？

感谢大佬写的书，我做完第一本学习以太坊的书开始阅读了，后续出书了一定买本纸质的

**Comment by purevirtual** [comment]
阅读完了00_geth.md这一章，有个疑问？ 

> 这个地方的写法还是非常有意思的，值得我们参考。我们为读者编写了一个简单的示例:如何使用 Channel 来管理 Go 程序的生命周期。

这里的示例应该就是这个 - https://github.com/ABCDELabs/Understanding-Ethereum-Go-version/blob/main/example/workflow/main.go

所以刨除掉函数的封装，本质上想写的是
`
go worker()
...
<-stopChan // 这里阻塞直到有信号通过chan传输过来
·

之前也看过一些其他company写的类似gin的框架，启动时候的代码类似这样
 用一个errChan接受httpserver的返回，如果是server里主动close 或者 运行出问题，那就waitHttp里面的errChan收到消息
如果是系统发出的kill信号等，那就是os.signal的chan收到信号


`
// Run 启动Http Server
func (s *Server) HttpRun() error {
	go func() {
		s.errChan <- s.runHttpServer()
	}()

	return s.waitHttp()
}

func (s *Server) waitHttp() error {
	var err error

	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)

	select {
	case sig := <-c:
		switch sig {
		case syscall.SIGTERM, syscall.SIGINT:
            // ...
		case syscall.SIGQUIT:
			s.httpSvr.Close()
		}

		logger.Infof("server closed got signal %s, shutdown success", sig)
		return fmt.Errorf("server closed got signal %s, shutdown success", sig)
	case err = <-s.errChan:
		return fmt.Errorf("server closed %s", err)
	}
}

`

看起来本质上相同的，不知道我理解是否正确？

**Comment by leo-shi-dacheng** [comment]
> -[Deprecated] [怎么用闲置的电脑进行挖矿 | mining] 这一章为何废弃了？是担心法律问题？
> 
> 感谢大佬写的书，我做完第一本学习以太坊的书开始阅读了，后续出书了一定买本纸质的

eth 赚了pos共识，目前使用的是  Casper FFG 机制。需要质押32eth  ，成为验证者， 有机会被选为提议者。

- 客户端发起请求
- 提议者（矿工）提议阶段 (Propose)
  - 在每个 slot 中，从验证者节点随机选出提议者
  - 提议者收集交易，尝试构建一个新的区块
  - 将新区块广播给所有验证者节点
- 验证阶段 (Validation)
  - 每个验证者节点接收到提议的区块后进行验证
  - 验证者对区块进行投票
  - 验证者将投票信息广播给其他验证者节点
- 安全检查点
  - 每32个 slot（约6.4分钟）组成一个 epoch
  - 每个 epoch 的第一个区块被标记为检查点
  - 验证者为检查点投票
  - 如果超过2/3的验证者投票支持，该检查点被标记为"safe"
- 最终检查点
  - 通常需要两个 epoch（约12.8分钟）
  - 当一个"safe"检查点被下一个检查点证实时
  - 它的状态变成"finalized"（最终确认)

**Comment by purevirtual** [comment]
看了01_account_state.md 这一章，

> eth 赚了pos共识，目前使用的是 Casper FFG 机制。需要质押32eth ，成为验证者， 有机会被选为提议者。

你的意思是 eth转了pos之后，是根据质押和eth的数量来进行选举。所以原有的挖矿不存在了？

**Comment by leo-shi-dacheng** [comment]
你可以理解为挖矿不存在了，出块机制完全变了

**Comment by hsyodyssey** [comment]
> 你可以理解为挖矿不存在了，出块机制完全变了

对的哈哈哈，Master分支已经没有pow了，所以就删了。
